Display rockets - Lists render.
joramot/space-traveler pull request #33
Opened 2023-10-11 22:10 UTC by joramot

**### Project Requirement**

- Imported useSelector to get the state of rockets
- Added html code  with the information in the return to render lists of rockets.
- Selected the state slices and render lists of rockets in corresponding routes.

2023-10-11 22:55 UTC, alex1779 requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @joramot  :wave: , 

Good job with this milestone so far! What a brilliant attempt!!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark:

## Required Changes ♻️
- [x] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 22:55 UTC, alex1779 commented on src/components/Rockets.js
>      </main>
Technically, The task requirement indicates that a list is required to display the items. Instead of using Articles you could use li objects inside of ul.

2023-10-12 02:01 UTC, joramot commented on src/components/Rockets.js
>      </main>
I decided to implement the rocket list using CSS classes and defining properties that display the information in list form.
There are properties for "ul" defined in the CSS file that are applied in different components of the project, making changes could affect them.

2023-10-12 02:42 UTC, alex1779 requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @joramot  :wave: , 

Good job with this milestone so far! What a brilliant attempt!!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark:

## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 02:42 UTC, alex1779 commented on src/components/Rockets.js
Please try to implement style as mentioned in the requirement. You can style the whole application "by hand" or you could use [React Bootstrap](https://react-bootstrap.github.io/), a UI library that could speed up the process. 

Your design:
![yourdesign](https://github.com/joramot/space-traveler/assets/80226144/6e75ceee-154a-4f20-a4bc-a3f2b6b1303f)
Design required:
![bestdesign](https://github.com/joramot/space-traveler/assets/80226144/4b30c7a1-c3ec-44d0-bb36-78022feaaffd)

2023-10-12 02:42 UTC, alex1779 commented on src/components/Rockets.js
> +      ))}
There is still no list implemented. Please correct this. Implement a list instead of using main and articles. Also avoid using "main" more than once in a single block, as this avoids some confusion.

2023-10-12 02:42 UTC, alex1779 commented on src/components/Rockets.js
> +          </main>
![stillold](https://github.com/joramot/space-traveler/assets/80226144/5dd14018-e9dc-4eec-9a58-468d9b60bd3c)
The button to "reserve the rocket" has still not been implemented. Please add the button and add the style according to the design.

2023-10-12 19:00 UTC, alex1779 approved these changes
# Approved 👏  


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-10-12 19:00 UTC, merged